apiVersion: v1
kind: Pod
metadata:
  name: share-process-namespace
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: radial/busyboxplus
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    stdin: true
    tty: true
